import './globals.css';
import Header from '@components/header';
import { fira_code, kanit, segio, inter } from '@/utils/fonts';
import Footer from '@components/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${segio.variable} ${fira_code.variable} ${kanit.variable} ${inter.variable} font-sans`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
